### PR TITLE
PORTALS-2905: include changes affecting SWC from synapse-react-client by renaming to defaultShowPlots

### PR DESCRIPTION
**Pull request by jinjunoh**
Implemented changes on swc to reflect the name changes made on synapse-react-client

### CODE REVIEW

**Comment by jay-hodgson** [comment]
Does this depend on a particular release of the react client library?

**Comment by jay-hodgson** [comment]
Does it make sense to check in IntelliJ iml files into the codebase?  If not, they should be removed from the PR, and probably added to .gitignore

**Review by jay-hodgson — CHANGES_REQUESTED** [review]
Added a couple of questions that I'd like to be answered before merge.  Changing the prop name is fine though!

**Comment by jinjunoh** [comment]
> Does this depend on a particular release of the react client library?

**Comment by jay-hodgson** [comment]
Depends on https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/682

**Review by jay-hodgson — APPROVED** [review]
Approved, but not to be merged until we are pointing to a compatible SRC release

**Comment by nickgros** [comment]
This should have been pulled into 488, changing the base branch and merging

**Pull request merged**
