### PR TITLE
better restore icon

### PR DESCRIPTION
**Pull request by kimyen**
screen shot 2016-09-15 at 3 08 55 pm
screen shot 2016-09-15 at 3 08 41 pm

### CODE REVIEW

**Comment by jay-hodgson** [comment]
I think the refresh on the trash bin makes it look a bit like a [recycle bin](https://www.google.com/search?q=recycle+bin&espv=2&biw=1440&bih=722&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiO1ILvtpLPAhURw2MKHTcOCJ4Q_AUIBygC)!  How does the "undo" icon on top of a trash bin look?

**Comment by kimyen** [comment]
This is "undo" on "trash"
screen shot 2016-09-15 at 3 41 25 pm

**Comment by jay-hodgson** [comment]
What do you think?  Looks like refreshing the trash can to me.  Maybe "trash" on "ban"?  Or maybe "arrow-up" on "trash-o"?

**Comment by kimyen** [comment]
"trash" on "ban"
screen shot 2016-09-15 at 3 47 20 pm

**Comment by kimyen** [comment]
I would like to make this one
screen shot 2016-09-15 at 3 48 23 pm
but I don't think I can do that. So any other icon would work.

**Comment by kimyen** [comment]
"arrow_up" on "trash_o"

screen shot 2016-09-15 at 3 54 53 pm

**Comment by jay-hodgson** [comment]
Your creation is the best!  
Could you resize, add to the IconsImageBundle, and reference as a g:Image in the ui xml?

**Comment by kimyen** [comment]
I found it online. I didn't know we could add our custom icon. I will try.

**Comment by jay-hodgson** [comment]
Ok.  Please make sure that we're in compliance with the terms of the license before using.

**Comment by kimyen** [comment]
I've checked. There is a license on the icon. And it says we cannot placed it "On any website in a complete or archived downloadable format" but could be reproduced in "On-line content."  
https://www.iconfinder.com/licenses/basic

**Comment by kimyen** [comment]
screen shot 2016-09-15 at 5 28 53 pm

**Pull request merged**
